import type { EncounterList } from "~/types/encounterTypes";

export const dummyCreatures: EncounterList = [
  {
    id: 1,
    initiative: 15,
    current_hp: 120,
    notes: "Protector of the ancient woods",
    current_conditions: [],
    tags: ["forest", "guardian"],
    isPlayer: false,
    name: "Forest Guardian",
    size: "Large",
    type: "Elemental",
    alignment: "Neutral Good",
    armor_class: 16,
    hit_points: 120,
    hit_dice: "16d10",
    speed: { walk: 30, climb: 20 },
    strength: 18,
    dexterity: 14,
    constitution: 16,
    intelligence: 12,
    wisdom: 15,
    charisma: 11,
    skills: { nature: 6, perception: 5 },
    damage_resistances: "cold, fire",
    languages: "Common, Elvish",
    challenge_rating: "5",
    actions: [
      {
        name: "Multiattack",
        desc: "The forest guardian makes two slam attacks.",
      },
      {
        name: "Slam",
        desc: "Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage.",
      },
    ],
    special_abilities: [
      {
        name: "Nature's Ward",
        desc: "The forest guardian has advantage on saving throws against spells and other magical effects.",
      },
    ],
  },
  {
    id: 2,
    initiative: 12,
    current_hp: 85,
    notes: "Lurks in the dark caves",
    current_conditions: ["invisible"],
    tags: ["cave", "stealthy"],
    isPlayer: false,
    name: "Cave Dweller",
    size: "Medium",
    type: "Monstrosity",
    alignment: "Chaotic Evil",
    armor_class: 14,
    hit_points: 85,
    hit_dice: "10d8",
    speed: { walk: 20, climb: 20 },
    strength: 15,
    dexterity: 18,
    constitution: 14,
    intelligence: 8,
    wisdom: 12,
    charisma: 6,
    skills: { stealth: 10 },
    damage_immunities: "poison",
    senses: "blindsight 60 ft.",
    languages: "Undercommon",
    challenge_rating: "3",
    actions: [
      {
        name: "Claw Attack",
        desc: "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) slashing damage.",
      },
    ],
    special_abilities: [
      {
        name: "Invisibility",
        desc: "The cave dweller can turn invisible as an action.",
      },
    ],
  },
  {
    id: 3,
    initiative: 8,
    current_hp: 138,
    notes: "A fearsome creature from the high mountains",
    current_conditions: [],
    tags: ["mountain", "troll"],
    isPlayer: false,
    name: "Mountain Troll",
    size: "Huge",
    type: "Giant",
    alignment: "Chaotic Neutral",
    armor_class: 13,
    hit_points: 138,
    hit_dice: "12d12",
    speed: { walk: 30 },
    strength: 22,
    dexterity: 8,
    constitution: 20,
    intelligence: 7,
    wisdom: 9,
    charisma: 6,
    skills: { athletics: 10 },
    damage_vulnerabilities: "fire",
    senses: "darkvision 60 ft.",
    languages: "Giant",
    challenge_rating: "7",
    actions: [
      {
        name: "Multiattack",
        desc: "The mountain troll makes two fist attacks.",
      },
      {
        name: "Fist",
        desc: "Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 18 (3d6 + 8) bludgeoning damage.",
      },
    ],
    special_abilities: [
      {
        name: "Regeneration",
        desc: "The mountain troll regains 10 hit points at the start of its turn if it has at least 1 hit point.",
      },
    ],
  },
  {
    id: 4,
    initiative: 10,
    current_hp: 65,
    notes: "Wanderer of the vast deserts",
    current_conditions: [],
    tags: ["desert", "nomad"],
    isPlayer: false,
    name: "Desert Nomad",
    size: "Medium",
    type: "Humanoid",
    alignment: "Neutral",
    armor_class: 12,
    hit_points: 65,
    hit_dice: "10d8",
    speed: { walk: 40 },
    strength: 12,
    dexterity: 14,
    constitution: 13,
    intelligence: 10,
    wisdom: 15,
    charisma: 11,
    skills: { survival: 7, perception: 6 },
    damage_resistances: "heat",
    languages: "Common",
    challenge_rating: "2",
    actions: [
      {
        name: "Scimitar Attack",
        desc: "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.",
      },
    ],
    special_abilities: [
      {
        name: "Desert Survival",
        desc: "The desert nomad has advantage on Survival checks in desert environments.",
      },
    ],
  },
  {
    id: 5,
    initiative: 18,
    current_hp: 52,
    notes: "A creature that blends with the shadows",
    current_conditions: ["hidden"],
    tags: ["shadow", "stalker"],
    isPlayer: false,
    name: "Shadow Stalker",
    size: "Small",
    type: "Fey",
    alignment: "Neutral Evil",
    armor_class: 15,
    hit_points: 52,
    hit_dice: "8d6",
    speed: { walk: 35, climb: 35 },
    strength: 10,
    dexterity: 19,
    constitution: 12,
    intelligence: 14,
    wisdom: 15,
    charisma: 13,
    skills: { stealth: 12, acrobatics: 8 },
    damage_immunities: "necrotic",
    condition_immunities: "blinded",
    senses: "darkvision 120 ft.",
    languages: "Sylvan, Common",
    challenge_rating: "4",
    actions: [
      {
        name: "Dagger Strike",
        desc: "Melee or Ranged Weapon Attack: +7 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 7 (1d4 + 5) piercing damage.",
      },
    ],
    special_abilities: [
      {
        name: "Shadow Blend",
        desc: "In dim light or darkness, the shadow stalker can take the Hide action as a bonus action.",
      },
    ],
  },
];
