"use client";

import Link from "next/link";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { EncounterTable } from "~/components/EncounterTable";
import { EncounterList } from "~/types/encounterTypes";

const dummyCreatures: EncounterList = [
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
  {
    name: "Goblin Scout",
    initiative: 15,
    hp: 7,
    hpMax: 7,
    ac: 15,
    notes: "Quick and sneaky, prefers ranged attacks",
    id: 1,
    conditions: [],
    tags: ["goblin", "scout", "ranged"],
    isPlayer: false,
  },
  {
    name: "Elven Ranger",
    initiative: 18,
    hp: 12,
    hpMax: 12,
    ac: 14,
    notes: "Skilled archer, has a pet wolf",
    id: 2,
    conditions: [],
    tags: ["elf", "ranger", "archer"],
    isPlayer: true,
  },
  {
    name: "Orc Berserker",
    initiative: 12,
    hp: 30,
    hpMax: 30,
    ac: 13,
    notes: "Fierce and aggressive, attacks with a greataxe",
    id: 3,
    conditions: [],
    tags: ["orc", "berserker", "melee"],
    isPlayer: false,
  },
];

export function HomeView() {
  return (
    <ResizablePanelGroup className="h-full" direction="horizontal">
      <ResizablePanel defaultSize={20}>
        <div className="flex h-full flex-col border-r">
          <h2 className="border-b px-6 py-4">Left Panel</h2>
          <div className="flex-1 overflow-auto"></div>
        </div>
      </ResizablePanel>
      <ResizableHandle />
      <ResizablePanel defaultSize={60}>
        <EncounterTable creaturesList={dummyCreatures} />
      </ResizablePanel>
      <ResizableHandle />
      <ResizablePanel defaultSize={20}>
        <div className="flex h-full flex-col border-l">
          <h2 className="border-b px-6 py-4">Right Panel</h2>
          <div className="flex-1 overflow-auto">
            <div className="space-y-2 px-6 py-4"></div>
          </div>
        </div>
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
