/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UZlIV0cIKod
 */
import Link from "next/link"
import { ResizablePanel, ResizableHandle, ResizablePanelGroup } from "@/components/ui/resizable"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Component() {
  return (
    <div className="flex flex-col h-full">
      <header className="flex items-center justify-between px-6 py-4 border-b">
        <h1 className="text-2xl font-semibold">Sales Transactions</h1>
      </header>
      <main className="flex-1 overflow-hidden">
        <ResizablePanelGroup className="h-full" direction="horizontal">
          <ResizablePanel defaultSize={20}>
            <div className="flex flex-col h-full border-r">
              <h2 className="px-6 py-4 border-b">Categories</h2>
              <div className="flex-1 overflow-auto">
                <nav className="px-6 py-4 space-y-1">
                  <Link
                    className="block py-1 text-gray-800 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700"
                    href="#"
                  >
                    Category 1
                  </Link>
                  <Link
                    className="block py-1 text-gray-800 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700"
                    href="#"
                  >
                    Category 2
                  </Link>
                  <Link
                    className="block py-1 text-gray-800 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700"
                    href="#"
                  >
                    Category 3
                  </Link>
                  <Link
                    className="block py-1 text-gray-800 hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700"
                    href="#"
                  >
                    Category 4
                  </Link>
                </nav>
              </div>
            </div>
          </ResizablePanel>
          <ResizableHandle />
          <ResizablePanel defaultSize={60}>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Invoice</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Method</TableHead>
                  <TableHead className="text-right">Amount</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">INV001</TableCell>
                  <TableCell>Paid</TableCell>
                  <TableCell>Credit Card</TableCell>
                  <TableCell className="text-right">$250.00</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">INV002</TableCell>
                  <TableCell>Pending</TableCell>
                  <TableCell>PayPal</TableCell>
                  <TableCell className="text-right">$150.00</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">INV003</TableCell>
                  <TableCell>Unpaid</TableCell>
                  <TableCell>Bank Transfer</TableCell>
                  <TableCell className="text-right">$350.00</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">INV004</TableCell>
                  <TableCell>Paid</TableCell>
                  <TableCell>Credit Card</TableCell>
                  <TableCell className="text-right">$450.00</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">INV005</TableCell>
                  <TableCell>Paid</TableCell>
                  <TableCell>PayPal</TableCell>
                  <TableCell className="text-right">$550.00</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </ResizablePanel>
          <ResizableHandle />
          <ResizablePanel defaultSize={20}>
            <div className="flex flex-col h-full border-l">
              <h2 className="px-6 py-4 border-b">Transaction Summary</h2>
              <div className="flex-1 overflow-auto">
                <div className="px-6 py-4 space-y-2">
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">Invoice:</span>
                    <span className="ml-2 text-gray-800 dark:text-gray-200">INV001</span>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">Status:</span>
                    <span className="ml-2 text-gray-800 dark:text-gray-200">Paid</span>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">Method:</span>
                    <span className="ml-2 text-gray-800 dark:text-gray-200">Credit Card</span>
                  </div>
                  <div>
                    <span className="text-gray-600 dark:text-gray-400">Amount:</span>
                    <span className="ml-2 text-gray-800 dark:text-gray-200">$250.00</span>
                  </div>
                </div>
              </div>
            </div>
          </ResizablePanel>
        </ResizablePanelGroup>
      </main>
    </div>
  )
}
